### ISSUE TITLE
Authorization Issues

### ISSUE THREAD

**Issue by medelman17** [AEB-labs/cruddl#66]
Hi, 

I can stand up the example schema and server in README, but cannot get queries to resolve due to an authorization error. Can someone advise?  

## Script

```js
const { ArangoDBAdapter, Project } = require("cruddl");
const { GraphQLServer } = require("graphql-yoga");

const project = new Project([
  {
    name: "schema.graphqls",
    body: `
    type Movie @rootEntity {
      title: String
      actors: Actor @relation
    }
    
    type Actor @rootEntity {
      name: String
      movies: Movie @relation(inverseOf: "actors")
    }`
  },
  {
    name: "permission-profiles.json",
    body: JSON.stringify({
      permissionProfiles: {
        default: {
          permissions: [
            {
              roles: ["users"],
              access: "readWrite"
            }
          ]
        }
      }
    })
  }
]);

const db = new ArangoDBAdapter({
  databaseName: "aqqaint",
  url: "http+tcp://root:@0.0.0.0:8529",
  user: "root",
  password: ""
});

const schema = project.createSchema(db);
db.updateSchema(project.getModel()); // create missing collections
const server = new GraphQLServer({ schema, context: () => ({ authRoles: ['users'] }) });
server.start(() => console.log('Server is running on http://localhost:4000/'));
```

## Query 

```graphql
{
  allMovies{
    id
  }
}
```

## Console Output: 

```sh 
schema-builder: Schema created successfully. []
Server is running on http://localhost:4000/
ArangoDBAdapter: ArangoDB version: 3.4.1. Workaround for sparse indices will not be enabled. []
query-resolvers: Executing query  []
query-resolvers: Operation: {
  allMovies {
    id
  }
} []
query-resolvers: DistilledOperation: query with selections {
  "allMovies": field allMovies with selections {
    "id": field id
  }
} []
query-resolvers: Request roles:  []
query-resolvers: Before authorization: {
  "allMovies": entities of type Movie as list with $movie_2 => 
    as {
      "id": id($movie_2)
    }
} []
query-resolvers: After authorization: {
  "allMovies": error "AuthorizationError: Not authorized to read Movie objects"
} []
ArangoDBAdapter: Executing AQL: @v_result1 = execute(
  RETURN {
    "allMovies": {__cruddl_runtime_error: "AuthorizationError: Not authorized to read Movie objects"}
  }
); []
query-resolvers: Execution successful []
query-resolvers: Result: {
  "allMovies": {
    "__cruddl_runtime_error": "AuthorizationError: Not authorized to read Movie objects"
  }
} []
Error: AuthorizationError: Not authorized to read Movie objects
    at Object.extractRuntimeError (/Users/michael/code/src/0001-Aqqaint/db/node_modules/cruddl/dist/src/query-tree/errors.js:40:12)
    at result.then.res (/Users/michael/code/src/0001-Aqqaint/db/node_modules/cruddl/dist/src/schema/preparation/schema-transformation-modules/add-runtime-error-resolvers.js:16:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by medelman17** [comment]
Just giving this a bump. It seems like it should be an easy fix, but I cannot figure out why the above is happening, how to disable authorization, and/or how anyone is making this work. Could someone please advise. Thanks!

**Comment by Yogu** [comment]
Oh sorry, I totally missed this issue. You recently closed it, did you resolve it?

If not, which version are you using? In the current release candidates (which you might get by just installing via `npm install cruddl`), the logic to get the roles changed a bit:

```typescript
const project = new Project([ /* your sources as in your example */], {
  getExecutionOptions: ({context}) => ({ authRoles: ['users'] })
});
```

This means cruddl no longer assumes anything about your context, but you can provide a method that gets the context and can return some options like the auth roles.

**Comment by RienNeVaPlus** [comment]
I'm having the same issue when following the example from the Readme. Providing a second argument for the `Project` constructor didn't do the trick for me either (expected 1 argument, got 2). I've installed using `npm install cruddl` and I'm on `0.8.0-alpha.31`.

Also, the `cruddl-demo` (https://github.com/AEB-labs/cruddl-demo) linked in the Readme seems to be offline. Can this still be found somewhere?

**Comment by Yogu** [comment]
Oh sorry, that was outdated again. The problem is that we pushed prereleases (the alpha versions) as "latest", and then npm installs them by default. If you install version 0.7.4, you get the current stable version that is also described in the README. In the alpha versions, it should be

```typescript
const project = new Project({
  sources: [ /* your sources as in your example */],
  getExecutionOptions: ({context}) => ({ authRoles: ['users'] })
});
```
